### ISSUE TITLE
Add milestone for release

### ISSUE THREAD

**Issue by kizu** [azproduction/1css#1]
While it is not too late, you should rename the current version to `0.1.0` and then add `1.0.0` to GitHub Milestone with the deadline at 2014-04-01.
1. The current state of project is very raw, you couldn't introduce breaking changes without increasing major version number, so staying in `0.x` until release would be perfect for development and semver.
2. Come on, release date of it really should be 2014-04-01 ;)

**Comment by azproduction** [comment]
Great idea!

**Comment by azproduction** [comment]
Done https://github.com/azproduction/1css/issues/milestones?with_issues=no

**Comment by kizu** [comment]
Do not forget to change/fill the changelog :)
