### ISSUE TITLE
CSS3 support

### ISSUE THREAD

**Issue by drgullin** [azproduction/1css#2]
Hey guys, this package is unbelievable.
It's handy for learning Russian, so I can code CSS now, instead of reading Tolstoy and Dostoevsky.

The missing feature is the CSS3 support.
I haven't found any info about the CSS3 selectors usage, like:
- E:first-child (Э:первый-ребенок)
- E:nth-child (Э:вон-тот-ребенок)
- E:last-child (Э:последний-ребенок)
- E:not (Э:не-хочу) 
- E:empty (Э:бездушный)
- E:root (Э:корень)
- and others.

What do you think about including them into 1css?

Thanks!

**Comment by azproduction** [comment]
1css is specification-driven project. Pseudo-selectors are defined in https://github.com/azproduction/1css/blob/master/spec/2.1-pseudo-selector.md

I take `:root`, `:empty` but as `:пустой`, `:last-child` and `:nth-child`.

Thanks!
