### ISSUE TITLE
Неверные названия

### ISSUE THREAD

**Issue by outring** [azproduction/1css#3]
хгруппа → згруппа
встроенный-блок → строчный-блок
гтяр → ягтр
без-засечкек → без-засечек
эл → рм (EqualsM → РавноМ)
высота-линии → высота-строки
ничего → нет
поумолчанию → обычный
рамка-блока → по-границе
контент-блока → по-содержимому
схлапывание-границы → схлапывание-границ
@медия → носитель

href → ссыл

**Comment by azproduction** [comment]
href - аттрибут же; Остальное забрал - спасибо!

**Comment by Grawl** [comment]
Вот, кстати, насчёт атрибутов. Можно и HTML перевести.

**Comment by azproduction** [comment]
> Можно и HTML перевести.

`<html>` ? или?

**Comment by Grawl** [comment]
@azproduction и не только этот. все.
HTML = HyperText Markup Language = Язык Разметки СверхТекста. (В идеале бы и слово “text” на русский язык перевести, потому как видно сразу транслитерацию)

``` html
<яргт>
    <голова>
        <свойство знаки="utf-8">
        <ссылка сотс="оформление.1css" отн="оформление/1css">
        <заголовок>Язык Разметки СверхТекста</заголовок>
    </голова>
    <тело>
        <заголовок>
            <з1>Язык Разметки СверхТекста</з1>
            <з2>давайте переведём на Русский язык всё</з2>
        </заголовок>
        <абз>Высоко в горах жил молодой и сильный горный орёл. Много лет он там жил, летал выше облаков, налетал на добычу быстрее молнии и никто не мог с ним совладать, никто не умел летать так, как он, никто не был в состоянии добывать добычу так легко и просто, как добывал её он. Прекрасен был горный орел и силён.</абз>
        <сценарий>…</сценарий>
    </тело>
</ягрт>
```

Впрочем, под это можно отдельную issue поднимать или даже repo.
